services:
  postgres:
    image: postgres:16
    container_name: bankapp_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
      POSTGRES_DB: bankdb
    volumes:
      - ./_data/postgres:/var/lib/postgresql/data
